<template>
  <el-menu
      :router="true"
      background-color="#545c64"
      text-color="#fff"
      active-text-color="#ffd04b"
      default-active="/indexMain"
      style="height: 100%"
      :collapse="is_collapse"
      :collapse-transition="false"
      :default-openeds="['1']">
    <!-- 一级菜单  -->
    <el-submenu :index="item.path" v-for="item in menuList" :key="item.path">
      <!-- 一级菜单的模板区域 -->
      <template slot="title">
        <!-- 图标 -->
        <i :class="item.icon"></i>
        <span slot="title">{{ item.name }}</span>
      </template>
      <!-- 二级菜单 -->
      <el-menu-item :index="it.path" v-for="it in item.sub" :key="it.path">
        <template slot="title">
          <i :class="it.icon"></i>
          <span slot="title">{{ it.name }}</span>
        </template>
      </el-menu-item>
    </el-submenu>
  </el-menu>
</template>

<script>
export default {
  name: "Aside",
  data(){
    return{
      isDisabled:false,
      menuList:[],
      user:JSON.parse(sessionStorage.getItem("CurUser"))
    }
  },
  props:{
    is_collapse:Boolean
  },
  methods:{
    getMenuList(){
      //超级管理员或管理员
      if(this.user.role == "0" || this.user.role == "1"){
        this.menuList = [
            {
              name:'员工信息管理',
              icon:"el-icon-user-solid",
              path:"1",
              sub:[
                  {
                    name:'员工管理',
                    icon:"el-icon-user-solid",
                    path:"/employeeMain"
                 },
                {
                  name:'个人中心',
                  icon:"el-icon-s-custom",
                  path:"/personalCenter"
                }
              ]
            },
            {
              name:'游客信息管理',
              icon:"el-icon-user",
              path:"2",
              sub:[
                  {
                     name:'游客信息',
                     icon:"el-icon-user",
                     path:"/visitorMain"
                  },
                  {
                    name:'停车位信息',
                    icon:"el-icon-place",
                    path:"/parkadeMain"
                  }
              ]
            },
           {
              name:'茶园信息管理',
              icon:"el-icon-location-information",
              path:"3",
              sub:[
                {
                  name:'茶园区域信息',
                  icon:"el-icon-pie-chart",
                  path:"/teaPantationParkMain"
                },
                {
                  name:'茶树信息',
                  icon:"el-icon-s-goods",
                  path:"/teaTreesMain"
                 },
                {
                  name:'景观树信息',
                  icon:"el-icon-more-outline",
                  path:"/otherTreesMain"
                }
              ]
           },
          {
            name:'茶叶信息管理',
            icon:"el-icon-goods",
            path:"4",
            sub:[
              {
                name:'茶叶采摘记录',
                icon:"el-icon-thumb",
                path:"/teaPluckMain"
              },
              {
                name:'茶叶加工记录',
                icon:"el-icon-present",
                path:"/teaProcessMain"
              },
              {
                name:'茶叶产品的信息',
                icon:"el-icon-tableware",
                path:"/tasteTeaMain"
              }
            ]
          },
           {
              name:"茶园设备管理",
              icon:"el-icon-s-tools",
              path:"5",
              sub:[
                {
                  name:'设备信息',
                  icon:"el-icon-takeaway-box",
                  path:"/equipmentMain"
                },
                {
                   name:'后勤仓库管理',
                  icon:"el-icon-house",
                  path:"/repositoryManageMain"
                }
              ]
           },
           {
             name:"数据统计",
             icon:"el-icon-s-data",
             path:"6",
             sub:[
               {
                 name:'人员信息统计',
                 icon:"el-icon-s-data",
                 path:"/personnelVisualizationMain"
               },
               {
                 name:'茶园生产信息统计',
                 icon:"el-icon-s-data",
                 path:"/teaProductionMain"
               },
               {
                 name:'设备资源统计',
                 icon:"el-icon-s-data",
                 path:"/resourcesVisualizationMain"
               }
             ]
           }
        ];
      }
      //员工
      else if (this.user.role == "2"){
        this.menuList = [
          {
            name:'员工信息管理',
            icon:"el-icon-user-solid",
            path:"1",
            sub:[
              {
                name:'员工查询',
                icon:"el-icon-user-solid",
                path:"/employeeStaffMain"
              },
              {
                name:'个人中心',
                icon:"el-icon-s-custom",
                path:"/personalCenter"
              }
            ]
          },
          {
            name:'游客信息管理',
            icon:"el-icon-user",
            path:"2",
            sub:[
              {
                name:'游客信息登记',
                icon:"el-icon-edit-outline",
                path:"/visitorRegisterMain"
              },
              {
                name:'游客出园登记',
                icon:"el-icon-edit-outline",
                path:"/visitorOutMain"
              },
              {
                name:'停车位信息',
                icon:"el-icon-place",
                path:"/parkadeMain"
              }
            ]
          },
          {
            name:'茶园信息管理',
            icon:"el-icon-location-information",
            path:"3",
            sub:[
              {
                name:'茶园区域信息',
                icon:"el-icon-pie-chart",
                path:"/teaPantationParkMain"
              },
              {
                name:'茶树信息',
                icon:"el-icon-s-goods",
                path:"/teaTreesMain"
              },
              {
                name:'景观树信息',
                icon:"el-icon-more-outline",
                path:"/otherTreesMain"
              }
            ]
          },
          {
            name:'茶叶信息管理',
            icon:"el-icon-goods",
            path:"4",
            sub:[
              {
                name:'茶叶采摘记录',
                icon:"el-icon-thumb",
                path:"/teaPluckMain"
              },
              {
                name:'茶叶加工记录',
                icon:"el-icon-present",
                path:"/teaProcessMain"
              },
              {
                name:'茶叶产品的信息',
                icon:"el-icon-tableware",
                path:"/tasteTeaMain"
              }
            ]
          },
          {
            name:"茶园设备管理",
            icon:"el-icon-s-tools",
            path:"5",
            sub:[
              {
                name:'设备信息',
                icon:"el-icon-takeaway-box",
                path:"/equipmentMain"
              },
              {
                name:'后勤仓库信息',
                icon:"el-icon-house",
                path:"/repositoryMain"
              }
            ]
          },
          {
            name:"数据统计",
            icon:"el-icon-s-data",
            path:"6",
            sub:[
              {
                name:'人员信息统计',
                icon:"el-icon-s-data",
                path:"/personnelVisualizationMain"
              },
              {
                name:'茶园生产信息统计',
                icon:"el-icon-s-data",
                path:"/teaProductionMain"
              },
              {
                name:'设备资源统计',
                icon:"el-icon-s-data",
                path:"/resourcesVisualizationMain"
              }
            ]
          }
        ];
      }
    }
  },
  beforeMount(){
    this.getMenuList();
  }
}
</script>

<style scoped>

</style>